### ISSUE TITLE
Add vedit birth charts

### ISSUE THREAD

**Issue by gauti019** [magicalmysticalcat/hades-js#25]
I'd like to know if there is any such feature available in this library, if not I am willing to contribute to this feature, if you could guide me towards how you proceed with the geometric calculations in your modules.

**Comment by magicalmysticalcat** [comment]
Hi @gauti019, thanks for reaching out.
The math behind Vedic astrology is more complex and different from the one used in Western astrology, which is the one Hades-js is solely focused on. The code in this library wouldn't be of much help as far as I know, but by all means if you find out something is of help, feel free to take it.
Being both based in different "views" of the Zodiac, you would need to base your calculations using a Sidereal ephemeris; Western uses Tropical.
I would encourage you to investigate and build your own Vedic library if there's nothing else out there, you would be doing a great service to everyone interested in it :).
